### ISSUE TITLE
Boolean Toggle 500 Error on TableBuilder

### ISSUE THREAD

**Issue by Failcookie** [anomalylabs/boolean-field_type#18]
The toggle switch on a TableBuilder is failing to toggle and throwing a 500 error. The error I am seeing in debugger is

`Invalid argument supplied for foreach() /vendor/anomaly/streams-platform/src/Ui/ControlPanel/Component/Section/SectionNormalizer.php#45`

Specifically this area
```
foreach ($sections as $slug => &$section) {
            if (isset($section['sections'])) {
                foreach ($section['sections'] as $key => &$child) {
                    $child['parent'] = array_get($section, 'slug', $slug);
```

**Comment by RyanThompson** [comment]
Is it out of date? Try asset:clear or twig:clean cause the ajax call should NOT be hitting admin (which I assume it is): https://github.com/anomalylabs/boolean-field_type/blob/master/resources/js/ajax.js#L7

**Comment by RyanThompson** [comment]
Can you show us what it's URL is requesting? IN the proper repo (main one) ^_^
