### ISSUE TITLE
Tip is out of alignment when field is required

### ISSUE THREAD

**Issue by j-hubb** [anomalylabs/boolean-field_type#7]
<img width="387" alt="screen shot 2016-02-21 at 09 16 32" src="https://cloud.githubusercontent.com/assets/6826637/13201880/e7b42800-d87b-11e5-946a-254c0b255eb3.png">

**Comment by RyanThompson** [comment]
I knew when I did those required tabs that it'd be trouble.. I think I might remove all those HTML5 hints. I originally did it for front end form assistance but the front end form repopulates forms just fine now so.. no REAL need for em.

**Comment by RyanThompson** [comment]
Fixed - I removed all those HTML5 flags.
